# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-28 19:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='date_requested',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='graphic_type',
            field=models.CharField(blank=True, choices=[('Poster', 'Poster'), ('Icon', 'Icon'), ('Logo', 'Logo'), ('Different', 'Different')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='wireframe',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
