# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-28 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_auto_20191128_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='request_title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
