# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-30 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_auto_20191128_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('accepted', 'accepted'), ('pending', 'pending'), ('rejected', 'rejected'), ('delivered', 'delivered')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='request_title',
            field=models.CharField(blank=True, default='pending', max_length=40),
            preserve_default=False,
        ),
    ]
