# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-30 16:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0008_auto_20191130_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_notes', models.TextField(blank=True)),
                ('final_product', models.ImageField(upload_to='')),
                ('status', models.CharField(blank=True, choices=[('accepted', 'accepted'), ('pending', 'pending'), ('rejected', 'rejected'), ('delivered', 'delivered')], max_length=9, null=True)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='requestmodel',
            name='status',
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='graphic_type',
            field=models.CharField(choices=[('Poster', 'Poster'), ('Icon', 'Icon'), ('Logo', 'Logo'), ('Different', 'Different')], default='Icon', max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='request',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='owner_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='request.RequestModel'),
        ),
    ]
