# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-30 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_auto_20191130_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='additional_notes',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='quote',
            name='date_send',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
